=== NONO654/CUSWeb/webapps/DELMFNApp/assets/xsd/ColumnConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELMIAMGAConfiguration" xmlns:tns="DS_DELMIAMGAConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Label">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="dataIndex"/>
                <xs:attribute type="xs:string" name="dicoType"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="Columns">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Column" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="dataIndex" use="optional"/>
                      <xs:attribute type="xs:string" name="dicoType" use="optional"/>
                      <xs:attribute type="xs:string" name="displayType" use="optional"/>
                      <xs:attribute type="xs:boolean" name="mandatory" use="optional"/>
                      <xs:attribute type="xs:string" name="Tooltip" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NONO654/CUSWeb/webapps/DELMFNApp/assets/xml/ProcessColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Manufacturing" xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
    <Columns>
        <Column dataIndex="revision.reference" dicoType="BusinessType"/>
        <Column dataIndex="V_description.reference" dicoType="PLMEntity" Tooltip="NameRevisionOwner.tooltip"/>
		    <Column dataIndex="V_ApplicabilityDate.reference" dicoType="PLMCoreReference"/>
        <Column dataIndex="ManufacturingItemUpdateStatus" displayType="BIEssentials"/>
        <Column dataIndex="current.reference" dicoType="BusinessType"/>
        <Column dataIndex="owner.reference" dicoType="BusinessType"/>
        <Column dataIndex="organization.reference" dicoType="BusinessType"/>
        <Column dataIndex="Scope.relation" displayType="Relation"/>
        <Column dataIndex="Implement.relation" displayType="Relation"/>
        <Column dataIndex="All.relation" displayType="Relation"/>
        <Column dataIndex="documents.document" displayType="DocMgmt"/>
        <Column dataIndex="V_isLastVersion.reference" dicoType="PLMCoreReference" displayType="NonEditable"/>
    </Columns>
</Config>

=== NONO654/CUSWeb/webapps/DELMFNApp/assets/xml/ProductPartColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="ProductsAndParts" xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label		dataIndex="V_Name.reference"		dicoType="PLMEntity"		displayType="NonEditable"/>
    <Columns>
        <Column	dataIndex="PLM_ExternalID.instance"		    dicoType="PLMInstance"		    displayType="NonEditable"/>
        <Column	dataIndex="revision.reference"		        dicoType="BusinessType"		    displayType="NonEditable"/>
        <Column dataIndex="ProductAssignmentStatus"       displayType="BIEssentials"/>
        <Column	dataIndex="V_description.reference"	      dicoType="PLMEntity"		      displayType="NonEditable" Tooltip="NameRevisionOwner.tooltip"/>
        <Column	dataIndex="owner.reference"			          dicoType="BusinessType"		    displayType="NonEditable"/>
        <Column	dataIndex="PLM_ExternalID.reference"			dicoType="PLMEntity"		      displayType="NonEditable"/>
        <Column	dataIndex="V_isLastVersion.reference"			dicoType="PLMCoreReference"		displayType="NonEditable"/>
        <Column	dataIndex="current.reference"		          dicoType="BusinessType"		    displayType="NonEditable"/>
    </Columns>
</Config>

=== NONO654/CUSWeb/webapps/DELMGAApp/assets/xml/RoutingsViewColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Routings" xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
      <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
      <Columns>
        <!-- <Column dataIndex="originated.reference"          displayType="DateTime" dicoType="BusinessType"/> -->
        <!-- <Column dataIndex="V_ApplicabilityDate.reference" displayType="DateTime" dicoType="DELLmiProductionSystemReference"/> -->
        <Column dataIndex="V_Balanceable.instance"             dicoType="DELLmiOperationPPRInstance"/>
        <!-- <Column dataIndex="V_QueuingModeIN.reference"     dicoType="DELLmiProductionSystemReference"/> -->
        <Column dataIndex="documents.document"                 displayType="DocMgmt"    minWidth="50"/>
        <Column dataIndex="current.reference"                  dicoType="BusinessType"  minWidth="50"/>
        <Column dataIndex="Routings_Items.relation"            displayType="Relation"   minWidth="50"/>
        <Column dataIndex="Routings_Resources.relation"        displayType="Relation"   minWidth="50"/>
      </Columns>
</Config>

=== NONO654/CUSWeb/webapps/DELMGAApp/assets/xml/ManufacturingViewColumnConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config name="Manufacturing" xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/ColumnConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
    <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
    <Columns>
        <Column dataIndex="V_Name.reference" displayType="PLMEntity"/>
        <Column dataIndex="V_description.reference" displayType="PLMEntity"/>
        <Column dataIndex="revision.reference" displayType="BusinessType"/>
        <Column dataIndex="owner.reference.relation" displayType="BusinessType"/>
        <Column dataIndex="Items_Routings.relation" displayType="Relation"/>
    </Columns>
</Config>
