=== NONO654/CUSWeb/webapps/DELWebMfgItemDefUI/assets/xsd/DELWebMfgItemDefDropTypeConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELMIAMFNConfiguration" xmlns:tns="DS_DELMIAMFNConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="DropConfig">
    <xs:complexType>
      <xs:all>
        <xs:element name="Body" type="tns:DropType" minOccurs="0"/>
        <xs:element name="Main" type="tns:DropType" minOccurs="0"/>
        <xs:element name="Alternate" type="tns:DropType" minOccurs="0"/>
        <xs:element name="Origin" type="tns:DropType" minOccurs="0"/>
        <xs:element name="CapableResource" type="tns:DropType" minOccurs="0"/>
        <xs:element name="Body" type="tns:DropType" minOccurs="0"/>
      </xs:all>
      <xs:attribute name="Title" type="xs:string" use="required" />
      <xs:attribute name="Description" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="DropType">
    <xs:sequence>
      <xs:element name="Type" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== NONO654/CUSWeb/webapps/DELWebMfgItemDefUI/assets/xml/DELWebMfgItemDefDropTypeConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<DropConfig xmlns="DS_DELMIAMFNConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMFNConfiguration ../xsd/DELWebMfgItemDefDropTypeConfig.xsd" Title="Allowed types in drop areas" Description="Sample configuration file delivered by DS.">
  <Body>
    <Type name="Part"/>
    <Type name="Product"/>
    <Type name="VPMReference"/>
    <Type name="Resource"/>
    <Type name="ResourceArea"/>
    <Type name="CreateAssembly"/>
    <Type name="CreateMaterial"/>
    <Type name="CreateKit"/>
    <Type name="Provide"/>
  </Body>
  <Main>
    <Type name="CreateAssembly"/>
    <Type name="CreateMaterial"/>
    <Type name="CreateKit"/>
    <Type name="Provide"/>
  </Main>
  <Alternate>
    <Type name="CreateAssembly"/>
  </Alternate>
  <Origin>
    <Type name="CreateAssembly"/>
  </Origin>
  <CapableResource>
    <Type name="VPMReference"/>
  </CapableResource>
</DropConfig>
