=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xsd/DELWebMfgAssetsDefUIEditLinkAttributes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELMIAMGAConfiguration" xmlns:tns="DS_DELMIAMGAConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:all>
        <xs:element name="DELAsmProcessCanUseCnx" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="HistorizationLinkRefRef" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="HistorizationLinkRefRef_inverse" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="DELLmiProductionSystemOutputCnxToMBOM" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="DELLmiMaterialPathCnxCust" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="DELLmiMaterialPathCnxCust_inverse" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="DELLmiTimeConstraintCnx" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="DELLmiTimeConstraintCnx_inverse" type="tns:EditLinkType" minOccurs="0"/>
        <!-- MGA-ImplementLink for Testing -->
        <xs:element name="ProcessImplementLinkOcc" type="tns:EditLinkType" minOccurs="0"/>
        <xs:element name="ProcessImplementLinkOcc_inverse" type="tns:EditLinkType" minOccurs="0"/>
      </xs:all>
      <xs:attribute name="Title" type="xs:string" use="required" />
      <xs:attribute name="Description" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="EditLinkType">
    <xs:sequence>
      <xs:element name="Attribute" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="name" type="xs:string" use="required"/>
          <xs:attribute name="readOnly" type="xs:boolean" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xml/DELWebMfgAssetsDefUIEditLinkAttributes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/DELWebMfgAssetsDefUIEditLinkAttributes.xsd" Title="Displayed attributes by types for Edit Links" Description="Sample configuration file delivered by DS.">
  <DELAsmProcessCanUseCnx>
    <Attribute name="PLMEntity.V_description"           readOnly="true"/>
    <Attribute name="DELAsmProcessCanUseCnx.V_ResourcesQuantity"  readOnly="true"/>
<!--    <Attribute name="CGJMyDeploymentExtension.CGJMyAttribute1"  readOnly="true"/> -->
<!--    <Attribute name="CGJMyDeploymentExtension.CGJMyAttribute2"  readOnly="true"/> -->
<!--    <Attribute name="CGJMyDeploymentExtension.CGJMyAttribute3"  readOnly="true"/> -->
  </DELAsmProcessCanUseCnx>
  <HistorizationLinkRefRef>
             <Attribute name="PLMEntity.V_description"  readOnly="true"/>
  </HistorizationLinkRefRef>
  <DELLmiProductionSystemOutputCnxToMBOM>
             <Attribute name="DELLmiProductionSystemOutputCnxToMBOM.V_InTransit"  readOnly="true"/>
  </DELLmiProductionSystemOutputCnxToMBOM>
<!--  MGA-ImplementLink just for testing
  <ProcessImplementLinkOcc>
             <Attribute name="PLMEntity.V_description"  readOnly="true"/>
  </ProcessImplementLinkOcc>
  -->
</Config>
