=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xsd/DELWebMfgAssetsDefUIRelationsColumnMapping.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELMIAMGAConfiguration" xmlns:tns="DS_DELMIAMGAConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="RelationsColumns">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="RelationsColumn" maxOccurs="unbounded">
          <xs:complexType>
              <xs:sequence>
              <xs:element name="LinkedObjectConstraint" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:attribute name="dataIndex" type="xs:string" use="required"/>
                  <xs:attribute name="dicoType" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Type" maxOccurs="unbounded">
                  <xs:complexType>
                  <xs:attribute name="name" type="xs:string" use="required"/>
                  <xs:attribute name="format" type="xs:string" use="required"/>
                  </xs:complexType>
              </xs:element>
              </xs:sequence>
              <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Description" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xml/DELWebMfgAssetsDefUIRelationsColumnMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<RelationsColumns xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/DELWebMfgAssetsDefUIRelationsColumnMapping.xsd" Title="Relations columns configuration" Description="Sample configuration file delivered by DS.">
    <RelationsColumn name="Routings_Items.relation">
        <Type name="ProcessImplementLink" format="Type"/>
        <Type name="DELLmiProductionSystemOutputCnxToMBOM" format="Type"/>
        <Type name="ProcessImplementLinkOcc" format="Type"/>
            <!-- MGA-ProductFlow for Testing
                <Type name="DELLmiTimeConstraintCnx" format="Type"/>
                <Type name="DELLmiTimeConstraintCnx_inverse" format="Type"/>
            -->    
    </RelationsColumn>
  <RelationsColumn name="Routings_Resources.relation">
    <Type name="DELAsmProcessCanUseCnx" format="Type"/>
  </RelationsColumn>
  <RelationsColumn name="Items_Routings.relation">
    <Type name="ProcessImplementLink_inverse" format="Type"/>
    <Type name="DELLmiProductionSystemOutputCnxToMBOM_inverse" format="Type"/>
    <Type name="ProcessImplementLinkOcc_inverse" format="Type"/>
  </RelationsColumn>
  <RelationsColumn name="Resources_Routings.relation">
    <Type name="DELAsmProcessCanUseCnx_inverse" format="Type"/>
  </RelationsColumn>
</RelationsColumns>
