=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xsd/DELWebMfgAssetsDefUIConfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="DS_DELMIAMGAConfiguration" xmlns:tns="DS_DELMIAMGAConfiguration" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="Config">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Preferences">
          <xs:complexType>
            <xs:all>
              <xs:element name="TableView" type="tns:BlocType" minOccurs="0"/>
              <xs:element name="LeftBloc" type="tns:BlocType" minOccurs="0"/>
              <xs:element name="RightBloc" type="tns:BlocType" minOccurs="0"/>
              <xs:element name="AuxiliaryView" type="tns:BlocType" minOccurs="0"/>
            </xs:all>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Title" type="xs:string" use="required"/>
      <xs:attribute name="Description" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="BlocType">
    <xs:sequence>
      <xs:element name="Label" type="tns:ColumnParamsType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="Columns" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Column" type="tns:ColumnParamsType" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="ColumnParamsType">
    <xs:attribute name="dataIndex" type="xs:string"/>
    <xs:attribute name="dicoType" type="xs:string"/>
    <xs:attribute name="displayType" type="xs:string"/>
    <xs:attribute name="minWidth" type="xs:nonNegativeInteger"/>
    <xs:attribute name="Tooltip" type="xs:string"/>
    <xs:attribute name="Type" type="xs:string"/>
  </xs:complexType>
</xs:schema>

=== NONO654/CUSWeb/webapps/DELWebMfgAssetsDefUI/assets/xml/DELWebMfgAssetsDefUIConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright DASSAULT SYSTEMES 2013 -->
<Config xmlns="DS_DELMIAMGAConfiguration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="DS_DELMIAMGAConfiguration ../xsd/DELWebMfgAssetsDefUIConfig.xsd" Title="UI Config" Description="Sample configuration file delivered by DS.">
  <Preferences>
    <TableView>
      <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
      <Columns>
        <!-- <Column dataIndex="originated.reference"          displayType="DateTime" dicoType="BusinessType"/> -->
        <!-- <Column dataIndex="V_ApplicabilityDate.reference" displayType="DateTime" dicoType="DELLmiProductionSystemReference"/> -->
        <Column dataIndex="V_Balanceable.instance"             dicoType="DELLmiOperationPPRInstance"/>
        <!-- <Column dataIndex="V_QueuingModeIN.reference"     dicoType="DELLmiProductionSystemReference"/> -->
        <Column dataIndex="documents.document"                 displayType="DocMgmt"    minWidth="50"/>
        <Column dataIndex="current.reference"                  dicoType="BusinessType"  minWidth="50"/>
        <Column dataIndex="Routings_Items.relation"            displayType="Relation"   minWidth="50"/>
        <Column dataIndex="Routings_Resources.relation"        displayType="Relation"   minWidth="50"/>
        <!-- <Column dataIndex="Effectivity" displayType="CFG"/> -->
        <!-- <Column dataIndex="CurrentEvolutionEffectivity" displayType="CFG"/> -->
        <!-- <Column dataIndex="ProjectedEvolutionEffectivity" displayType="CFG"/> -->
        <!-- <Column dataIndex="VariantEffectivity" displayType="CFG"/> -->
      </Columns>
    </TableView>
    <LeftBloc>
      <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
      <Columns>
        <Column dataIndex="V_Name.reference"        dicoType="PLMEntity" />
        <Column dataIndex="V_description.reference" dicoType="PLMEntity" Tooltip="NameRevisionOwner.tooltip"/>
        <Column dataIndex="revision.reference"      dicoType="BusinessType"/>
        <Column dataIndex="owner.reference"         dicoType="BusinessType" minWidth="50"/>
        <Column dataIndex="Items_Routings.relation" displayType="Relation" />
      </Columns>
    </LeftBloc>
    <RightBloc>
      <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
      <Columns>
        <Column dataIndex="V_MTBF.reference"                  dicoType="Resource"/>
        <Column dataIndex="V_DELRmi_MountingMethod.reference" dicoType="Robot"/>
        <Column dataIndex="V_DELRmi_NbDOFs.reference"         dicoType="Robot"/>
        <Column dataIndex="Resources_Routings.relation"       displayType="Relation"/>
      </Columns>
    </RightBloc>
    <AuxiliaryView>
        <Label dataIndex="V_Name.reference" dicoType="PLMEntity"/>
    </AuxiliaryView>
  </Preferences>
</Config>
